baseURL = 'https://esjuau.github.io/blog/'
languageCode = 'en-us'
title = 'My Blog About Anything'
theme = 'papermod'
summarySeparator = "<!--more-->"


[security]
  enableInlineShortcodes = true
[security.exec]
  allow = [
    '^(dart-)?sass(-embedded)?$',
    '^go$',
    '^git$',
    '^npx$',
    '^postcss$',
    '^tailwindcss$',
    '^asciidoctor$'
  ]
  osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|SYSTEMDRIVE)$']
[security.funcs]
  getenv = ['^HUGO_', '^CI$']
[security.http]
  methods = ['(?i)GET|POST']
urls = ['.*']

# --- PaperMod Teeman Asetukset ---
[params]
  math = true

# --- AsciiDoc Asetukset ---
[markup]
[markup.asciidocExt]
  safeMode   = "safe"
  extensions = ["asciidoctor-katex"]

  [markup.asciidocExt.attributes]
  stem = "latexmath"
